### ISSUE TITLE
does this module work?

### ISSUE THREAD

**Issue by matthewmueller** [thysultan/jsx.js#1]
like the idea of this module, but it doesn't seem like the regexp matches even the simplest of jsx.

```
const jsx = require('jsx.js')
const js = jsx(`<h2 />`, 'h')
console.log(js); // <h2 />
```

**Comment by thysultan** [comment]
It works, that's a bug... it's meant to parse used JSX within js source context, i don't think i took into account using it with a simple case like that, will push an update to improve the JSX finder, i'm using [regex](https://github.com/thysultan/jsx.js/blob/master/jsx.js#L54) at the moment for that but the parser/compiler is non-regex.

ex. It can find

```js
var Hello = <h1>Hello</h1>;
```

**Comment by matthewmueller** [comment]
oh okay, sounds good. yah i was trying it with just jsx strings, which it was failing on like all of them haha, but in practice, it'd be within the JS context, so I'll try that – thanks!
